config/routes.rb
Rails.application.routes.draw do
  resources :negocios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'home', to: 'home#show'
  get 'me', to: 'me#show', as: 'me'

  root 'home#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categoria.rb
class Categoria < ApplicationRecord
    has_many :negocios
end

app/models/negocio.rb
class Negocio < ApplicationRecord
    belongs_to :user
    belongs_to :categoria

    validates :nome, presence: true, length: { maximum: 80 }
    validates :descricao, length: { maximum: 1000 }
    validates :site, length: { maximum: 80 }
    validates :cep, length: { maximum: 80 }
    validates :logradouro, length: { maximum: 80 }
    validates :numero, length: { maximum: 80 }
    validates :complemento, length: { maximum: 80 }
    validates :bairro, length: { maximum: 80 }
    validates :cidade, length: { maximum: 80 }
    validates :estado, length: { maximum: 80 }
    validates :facebook, length: { maximum: 80 }
    validates :instagram, length: { maximum: 80 }
    validates :whatsapp, length: { maximum: 80 }
    validates :telefone, length: { maximum: 80 }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :negocios
	def self.find_or_create_from_auth_hash(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.nome = auth.info.first_name
			user.email = auth.info.email
			user.save!
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user, :is_current_user_owner
  
    def authenticate
        redirect_to :login unless user_signed_in?
    end
  
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def is_current_user_owner(negocio)
        negocio.user == current_user
    end
  
    def user_signed_in?
        # converts current_user to a boolean by negating the negation
        !!current_user
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def show
    end
end

app/controllers/me_controller.rb
class MeController < ApplicationController
    before_action :authenticate
    def show
    end
end

app/controllers/negocios_controller.rb
class NegociosController < ApplicationController
  before_action :set_negocio, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, only: [:new, :create, :edit, :update, :destroy]
  # GET /negocios
  # GET /negocios.json
  def index
    @negocios = Negocio.all
    
    estados = Negocio.all.map {|n| n.estado }
    @estados = estados.uniq - ["", nil]
  end

  # GET /negocios/1
  # GET /negocios/1.json
  def show
  end

  # GET /negocios/new
  def new
    @negocio = Negocio.new
    @categorias = Categoria.all.map { |cat| [cat.nome, cat.id] }
  end

  # GET /negocios/1/edit
  def edit
    @categorias = Categoria.all.map { |cat| [cat.nome, cat.id] }
  end

  # POST /negocios
  # POST /negocios.json
  def create
    @negocio = Negocio.new(negocio_params)
    @negocio.categoria_id = params[:categoria_id]
    @negocio.user = current_user
    respond_to do |format|
      if @negocio.save
        format.html { redirect_to negocios_path, notice: 'Negócio criado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /negocios/1
  # PATCH/PUT /negocios/1.json
  def update
    if is_current_user_owner(@negocio)
      respond_to do |format|
        @negocio.categoria_id = params[:categoria_id]
        if @negocio.update(negocio_params)
          format.html { redirect_to negocios_path notice: 'Negócio alterado com sucesso.' }
        else
          format.html { render :edit }
        end
      end
    end
  end

  # DELETE /negocios/1
  # DELETE /negocios/1.json
  def destroy
    if is_current_user_owner(@negocio)
      @negocio.destroy
      respond_to do |format|
        format.html { redirect_to negocios_url, notice: 'Negócio apagado com sucesso.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_negocio
      @negocio = Negocio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def negocio_params
      params.require(:negocio).permit(:nome, :descricao, :site, :cep, :logradouro, 
        :numero, :complemento, :bairro, :cidade, :estado, :categoria_id, :facebook, 
        :instagram, :whatsapp, :telefone, :email)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
    def create
        @user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
        session[:user_id] = @user.id
        redirect_to new_negocio_path
    end
  
    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end
  
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/me_helper.rb
module MeHelper
end

app/helpers/negocios_helper.rb
module NegociosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/show.html.erb
<div class="container">
  <h1>Tamo Aí!</h1>
  <p class="lead text-muted">Vamos ajudar a manter a economia funcionando e <b>preservar empregos.</b></p>
  <div class="card-deck mb-6 text-center">
    <div class="card">
      <%= image_tag "novo.jpg", class: "card-img-top", alt: "Mulher em casa com tablet" %>
      <div class="card-body">
        <p class="card-text">Ache um negócio que pode te atender, mesmo estando em casa.</p>
        <%= link_to "Procurar um negócio", negocios_path, class: "btn btn-primary btn-lg" %>
      </div>
    </div>
    <div class="card">
      <%= image_tag "delivery.jpg", class: "card-img-top", alt: "Homem fazendo entrega" %>
      <div class="card-body">
        <p class="card-text">Divulgue seu negócio que, mesmo na quarentena, está atendendo.</p>
        <%= link_to "Divulgar meu negócio", new_negocio_path, class: "btn btn-primary btn-lg" %> 
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tamo Aí</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/212d35174f.js" crossorigin="anonymous"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-162669026-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-162669026-1');
    </script>

  </head>

  <body>
    <main role="main">
      <section class="jumbotron text-center">
        <%= yield %>
      </section>
    </main>
    <footer>
      <div class="container text-center">
        <p>
          <a href="https://www.freepik.com/free-photos-vectors/people">People vector created by freepik - www.freepik.com</a>
        </p>
        <p>
          <a href="https://www.freepik.com/free-photos-vectors/background">Background vector created by pikisuperstar - www.freepik.com</a>
        </p>
      </div>
    </footer>
  </body>
</html>

app/views/me/show.html.erb
<% if current_user %>
	<% current_user.attributes.each do |k, v| %>
		<b><%= k %>:</b> <%= v %> <br>
	<% end %>
<% end %>

app/views/negocios/_form.html.erb
<script>
function validateForm() {
  var x = document.forms["negocio"]["negocio_logradouro"].value;
  if (x == "") {
    alert("O Endereço deve ser preenchido. Informe o CEP e clique \'Preencher endereço\'");
    return false;
  } else {
    return true;
  }
}
</script>

<div class="container">
  <%= form_with(model: negocio, local: true, class: "text-left", html: { onsubmit:"return validateForm();document.getElementByName('commit').disabled = false;", name: "negocio"}) do |form| %>
    <% if negocio.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(negocio.errors.count, "error") %> prohibited this negocio from being saved:</h2>

        <ul>
        <% negocio.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-sm-8">
        <div class="form-group">
          <%= form.label :nome %>
          <%= form.text_field :nome, 
            class: "form-control mb-2", 
            required: true,
            oninvalid: "this.setCustomValidity('O nome deve ser informado')",
            oninput: "this.setCustomValidity('')",
            maxlength: 80 %>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <%= form.label :categoria %><br>
          <%= select_tag(:categoria_id, options_for_select(@categorias, @negocio.categoria_id), class: "form-control" )%>
        </div>
      </div>
</div>

<div class="row">


      <div class="col-sm-4"> 
        <div class="form-group">
          <label>Site (opcional)</label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon3">https://</span>
            </div>
            <%= form.text_field :site, class: "form-control", maxlength: 80 %>
          </div>
        </div>
      </div>
      <div class="col-sm-4"> 
        <div class="form-group">
          <label>Email (opcional)</label>
          <%= form.text_field :email, class: "form-control", maxlength: 80 %>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <label>Facebook (opcional)</label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon3">fb.com/</span>
            </div>
            <%= form.text_field :facebook, class: "form-control", maxlength: 80 %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      
      <div class="col-sm-4">
        <div class="form-group">
          <label>Instagram (opcional)</label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon3">@</span>
            </div>
            <%= form.text_field :instagram, class: "form-control", maxlength: 80 %>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <label>Whatsapp (opcional)</label>
          <%= form.text_field :whatsapp, class: "form-control", maxlength: 80 %>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <label>Telefone (opcional)</label>
          <%= form.text_field :telefone, class: "form-control", maxlength: 80 %>
        </div>
      </div>
    </div>
    
    <div class="form-group">
      <label>Fale sobre seu negócio. Use esse espaço para vender seu produto ou serviço! (opcional)</label>
      <%= form.text_area :descricao, class: "form-control", maxlength: 1000 %>
    </div>

    <div class="row">
      <div class="col-sm-4">
        <div class="form-group">
          <label>CEP (somente números)</label>
          <div class="input-group sm-4">
            <%= form.text_field :cep, 
              class: "form-control",
              required: true,
              oninvalid: "this.setCustomValidity('O CEP deve ser informado')",
              oninput: "this.setCustomValidity('')" %>
            <div class="input-group-append">
              <button class="btn btn-primary" type="button" data-remote="true">Preencher endereço</button>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="form-group">
          <label>Endereço</label>
          <%= form.text_field :logradouro, 
            class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-2">
        <div class="form-group">
          <label>Número (opcional)</label>
          <%= form.text_field :numero, class: "form-control", maxlength: 80 %>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="form-group">
          <label>Complemento (opcional)</label>
          <%= form.text_field :complemento, class: "form-control", maxlength: 80 %>
        </div>
       </div> 
    </div>  
    
    <div class="row">
      <div class="col-sm-4">
        <div class="form-group">
          <%= form.label :bairro %>
          <%= form.text_field :bairro, readonly: "true", class: "form-control" %>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <%= form.label :cidade %>
          <%= form.text_field :cidade, readonly: "true", class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="form-group">
          <%= form.label :estado %>
          <%= form.text_field :estado, readonly: "true", class: "form-control" %>
        </div>
      </div>
    </div> 

    <div class="actions">
      <%= form.submit "Salvar", class: "btn btn-lg btn-primary", id: "commit"   %>
      <%= link_to "Cancelar", negocios_path, class: "btn btn-lg btn-secondary"%>
    </div>
  <% end %>
</div>

app/views/negocios/edit.html.erb
<h1>Dados do negócio</h1>

<%= render 'form', negocio: @negocio %>

app/views/negocios/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <% @estados.each do |estado| %>
    <p><h3><%= estado %></h3></p>
  

    <% @negocios.each do |negocio| %>
      <% if (estado == negocio.estado )%>
        <div class="card">
          <div class="card-body text-left">
            <h3 class="card-title"><%= negocio.nome %></h3>
            <p class="text-muted font-italic"><%= negocio.categoria.nome %></p>
            <p class="card-text"><%= negocio.descricao %></p>

            <div class="row">
              <div class="col-sm-6">
                <% if negocio.site && !negocio.site.empty? %>
                  <a href="https://<%= negocio.site %>"/" target="_blank" >
                    <i class="fas fa-globe-americas"></i>
                    <label><%= negocio.site %></label>
                  </a>
                <% end %>
              </div>
              <div class="col-sm-6">
              <% if negocio.email && !negocio.email.empty? %>
                  <a href="mailto:<%= negocio.email %>" >
                  <i class="far fa-envelope"></i>
                  <label><%= negocio.email %></label>
                </a>
                <% end %>
              </div>
            </div>

            <div class="row">
              <div class="col-sm-6">
                <% if negocio.facebook && !negocio.facebook.empty? %>
                  <a href="https://www.fb.com/<%= negocio.facebook %>"/" target="_blank">
                    <i class="fab fa-facebook-square"></i>
                    <label><%= negocio.facebook %></label>
                  </a>
                <% end %>
              </div>
              <div class="col-sm-6">
              <% if negocio.instagram && !negocio.instagram.empty? %>
                <a href="https://www.instagram.com/<%= negocio.instagram %>"/" target="_blank" >
                  <i class="fab fa-instagram"></i>
                  <label><%= negocio.instagram %></label>
                </a>
                <% end %>
              </div>
            </div>

            <div class="row">
              <div class="col-sm-6">
              <% if negocio.whatsapp && !negocio.whatsapp.empty? %>
                <i class="fab fa-whatsapp"></i>
                <label><%= negocio.whatsapp %></label>
                <% end %>
              </div>
              <div class="col-sm-6">
                <% if negocio.telefone && !negocio.telefone.empty? %>
                  <i class="fas fa-phone"></i>
                  <label><%= negocio.telefone %></label>
                <% end %>
              </div>
              </div> 
            <% if is_current_user_owner(negocio)%>
              <div class="row">
                <div class="col-sm-6">
                  <%= link_to "Editar", edit_negocio_path(negocio), class: "btn btn-primary btn-lg" %> 
                </div>
                <div class="col-sm-6">
                  <%= link_to "Deletar", negocio, method: :delete, class: "btn btn-danger btn-lg", data: { confirm: "Are you sure?" } %>
                </div>
              </div>
            <% end %>
          </div>
          
        </div>
      <% end %>
    <% end %>
  <% end %>
  <p>
    <div class="card">
      <div class="card-body">
        <p class="card-text">Divulgue seu negócio que, mesmo na quarentena, está funcionando.</p>
        <%= link_to "Divulgar meu negócio", new_negocio_path, class: "btn btn-primary btn-lg" %> 
      </div>
    </div>
  <p>    
</div>

app/views/negocios/new.html.erb
<h1>Dados do negócio</h1>

<%= render 'form', negocio: @negocio %>

app/views/negocios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @negocio.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @negocio.descricao %>
</p>

<p>
  <strong>Site:</strong>
  <%= @negocio.site %>
</p>

<p>
  <strong>Dono:</strong>
  <%= @negocio.user.nome %>
</p>

<p>
  <strong>CEP:</strong>
  <%= @negocio.cep %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @negocio.logradouro %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @negocio.numero %>
</p>

<p>
  <strong>Complemento:</strong>
  <%= @negocio.complemento %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @negocio.bairro %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @negocio.cidade %>
</p>

<p>
  <strong>UF:</strong>
  <%= @negocio.estado %>
</p>

<% if is_current_user_owner(@negocio) %>
  <%= link_to 'Edit', edit_negocio_path(@negocio) %> |
<% end %>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>